#!/bin/sh
set -ex
#############################################################################
##

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

export DIR=${DISTROOT}/gapcore

# create and go to build directory
if ! mkdir -p ${DIR}; then
  echo 'Cannot create temporary directory '${DIR}
  exit 1
fi

# copying ./setvar to the build directory for the meta-information archive

cp ./setvar ${DIR}

echo 'Changing the directory to '${DIR}
  
echo 'cd '${DIR}
cd ${DIR}
rm -rf ${DISTNAME}

# Clone the repository.
echo "$0: cloning the repository for version 4.$FULLVERSION of $DATE"
line='git clone --depth 1 -b '${GAPGITVERSION}' '${GITROOT}' '${DISTNAME}
echo $line
$line

if [ \! -d ${DISTNAME} ];  then
    echo "PANIC: Git did not create a distribution directory"
    exit 1
fi

# What is *this moment*? If the subsequent wrapping and tests will be
# successful, recorded time of the checkout will be used to tag 
# corresponding revisions as included in the particular release.
export COREDATE=`date +"%d-%b-%Y"`
export CORETIME=`date -u +"%Y_%m_%d-%H_%M"`
export COREYEAR=`date +"%Y"`
echo "export DISTNAME=\"$DISTNAME\"" > core_checkout_time.txt
echo "export ARCHNAME=\"$ARCHNAME\"" >> core_checkout_time.txt
echo "export CORETIME=\"$CORETIME\"" >> core_checkout_time.txt
echo "export COREDATE=\"$COREDATE\"" >> core_checkout_time.txt
echo "export COREYEAR=\"$COREYEAR\"" >> core_checkout_time.txt

# logging the parent revision to a file
cd ${DISTNAME}
echo 'The working directory is set to the following revision:'
git log -1 > ../gitparent.log
cd ..
cat gitparent.log
echo 'This revision is logged to '${DIR}'/gitparent.log'

# We do not use Git later so we may erase .git* files and .git directory
echo 'Removing .git* files and .git directory'
rm -rf ${DISTNAME}/.git*

exit 0
