#!/bin/sh -ex
#############################################################################
##

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

export RELEASEBRANCH=${DISTROOT}/releasebranch

cp ./classifyfiles.py ${RELEASEBRANCH}
cp ./pattern* ${RELEASEBRANCH}

line='cd '${RELEASEBRANCH}
echo $line
$line 

pre=${DISTNAME}

echo 'Classifying files into text/binary for main archive or not shipped'

python ./classifyfiles.py $pre
             
exit 0
