#!/bin/sh
set -ex
#############################################################################
##

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

export DIR=${DISTROOT}/gapcore

cp ./classifyfiles.py ${DIR}
cp ./pattern* ${DIR}

line='cd '${DIR}
echo $line
$line 

pre=${DISTNAME}

echo 'Classifying files into text/binary for main archive or not shipped'

python ./classifyfiles.py $pre
             
exit 0
