#!/bin/sh
set -ex
#############################################################################
##

# STAGE 1 - checkout and archive the release branch
./setvar
./checkoutgit
./classifyfiles
./zipreleasebranch
./zipmetainfo

# STAGE 2 - make preparations in the GAP core
# (note that the next script also unpacks the meta-information archive)
./unpackreleasebranch
./zipgapcore
./updatemetainfo

# STAGE 3 - merge GAP core with packages 
# (note that the next script also unpacks the meta-information archive)
./unpackgapcore
./unpackpackages
./checkpermissions
./makedoc
./addmanualfiles
./zipgapsourcedistro
./finalisemetainfo
