#!/bin/sh -ex
#############################################################################
##

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

line='cd '${DISTROOT}/gapcore
echo $line
$line 

# dirs to 755, files to 644
echo 'chmod 755 for directories and chmod 644 for files...'
find ${DISTNAME} -type d -exec chmod 755 {} ";"
find ${DISTNAME} -type f -exec chmod 644 {} ";"

# very few files are executables

echo 'and there are a few executables ...' 
find \
  ${DISTNAME}/autogen.sh \
  ${DISTNAME}/bin/BuildPackages.sh \
  ${DISTNAME}/cnf/{config.guess,config.sub,install-sh} \
  ${DISTNAME}/doc/manualindex \
  ${DISTNAME}/etc/convert.pl \
  -exec chmod 755 {} ";"

exit 0
