#
# Makefile for wrapping the GAP release
#
# minor : based on the head of the corresponding stable branch
# major : based on the head of the master branch

minor:
	cp setvarminor setvar
	./doit

major:
	cp setvarmajor setvar
	./doit

clean:
	rm setvar
