#!/bin/sh -ex
#############################################################################
##

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

line='cd '${DISTROOT}'/gapsourcedistro/'${DISTNAME}''
echo $line
$line 

# build the documentation
./autogen.sh
./configure
make
cd pkg/io-*
./configure
make
cd ../..
make manuals
make clean

exit 0

