#!/bin/sh -ex
#############################################################################
#
# version to wrap - adjust major and minor numbers as needed
#
# major release number (i.e. the last number in GAP 4.4, 4.5, 4.6)
export MAJORVERSION="8"
# minor release number (i.e. the last number in GAP 4.4.12, 4.5.5, 4.5.17)
export MINORVERSION="8"

#-----------------------------------------------------------------------------
# everything below normally need not to be changed.

# full version
export FULLVERSION="$MAJORVERSION.$MINORVERSION"

# branch or tag to checkout from the repository:
# - to get the current snapshot of the named branch, use the name of 
#   the branch you need, e.g. "stable-4.5", "default" or "integration"
# - to get the state used for the previous release (e.g. to merge with 
#   the new packages archive, use corresponding tag, e.g. "v4.5.6" 
export GAPGITVERSION="stable-4.$MAJORVERSION"

# directory name (e.g. "gap4r5")
export DISTNAME="gap4r$MAJORVERSION"

# archive name (e.g. "gap4r5p6")
export ARCHNAME="gap4r${MAJORVERSION}p${MINORVERSION}"

# location of the merged packages archive (assumed to be on the same machine)
export MERGEDPKGLOC="/circa/home/gap-jenkins/workspace/GAP-pkg-merge-stable/DistributionUpdate/PackageUpdate"

# Where to put the temporary export tree and archives
export DISTROOT="/circa/home/gap-jenkins/workspace/GAP-minor-release/wrap/$DISTNAME"

# the source repository (access must be configured in advance)
export GITROOT="https://github.com/gap-system/gap.git"

#-----------------------------------------------------------------------------
# everything below should be system independent.

# unset locale settings
export LANG="C"
export LC_ALL="C"

umask 022

echo "*** Environment set for creating Version GAP 4."${FULLVERSION}
