#!/bin/sh
set -ex
#############################################################################
##
## Update version-related information and release date.
##
#############################################################################

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

line='cd '${DISTROOT}/gapcore
echo $line
$line 

source ./core_checkout_time.txt

cd ${DISTNAME}

# Update suggestions how to cite GAP
sed -i -e "s/4.dev/4.$FULLVERSION/g" CITATION
sed -i -e "s/this year/$COREYEAR/g" CITATION

cd lib/
## Adjusting 'Version', 'NeedKernelVersion' and 'Date' in the library
##    Version := MakeImmutable("4.dev"),
##    Date := MakeImmutable("today"),
##    NeedKernelVersion := MakeImmutable("4.dev"),
sed -i -e "s/4.dev/4.$FULLVERSION/g" system.g
sed -i -e "s/today/$COREDATE/g" system.g

cd ../src/
## Adjusting 'SyKernelVersion' and 'SyBuildDateTime' in the kernel
## const Char * SyKernelVersion = "4.dev";
## const Char * SyBuildDateTime = "today";
sed -i -e "s/today/$COREDATE/g" gap_version.c.in
sed -i -e "s/4.dev/4.$FULLVERSION/g" system.c

cd ../cnf
# Adjusting the script the generates a version string for GAP
# DEF_VER=v4.dev
sed -i -e "s/4.dev/4.$FULLVERSION/g" GAP-VERSION-GEN

cd ../doc/
## Setting up version number, release date, release year and
## GAP directory name as entities to be used in GAP manuals
## <!ENTITY VERSIONNUMBER "4.dev">
## <!ENTITY RELEASEDAY "today">
## <!ENTITY RELEASEYEAR "this year">
## <!ENTITY GAPDIRNAME "gap4dev">
sed -i -e "s/4.dev/4.$FULLVERSION/g" versiondata
sed -i -e "s/today/$COREDATE/g" versiondata
sed -i -e "s/this year/$COREYEAR/g" versiondata
sed -i -e "s/gap4dev/$DISTNAME/g" versiondata

cd ..

exit 0
