#!/bin/sh -ex
#############################################################################
##

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

export GAPCORE=${DISTROOT}/gapcore

line='cd '${GAPCORE}
echo $line
$line 

source ./core_checkout_time.txt

ziparchive=${ARCHNAME}-core.zip
# we clean previous attempts to wrap the same checkout
rm -f ${ziparchive}
echo 'Creating the GAP core archive '${GAPCORE}/$ziparchive

pre=${DISTNAME}
cd $pre/doc
pdftex gapmacrodoc.tex
pdftex gapmacrodoc.tex
cd ../..
echo $pre/doc/gapmacrodoc.pdf >> listbinaryfiles.txt

echo 'Adding text files to the archive '${GAPCORE}/$ziparchive
cat listtextfiles.txt | zip -q ${ziparchive} -@

echo 'Adding binary files to the archive '${GAPCORE}/$ziparchive
cat listbinaryfiles.txt | zip -q ${ziparchive} -@
             
exit 0


