#!/bin/sh
set -ex
#############################################################################
##

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

export GAPCORE=${DISTROOT}/gapcore

line='cd '${GAPCORE}
echo $line
$line 

source ./core_checkout_time.txt

ziparchive=${ARCHNAME}-core.zip
# we clean previous attempts to wrap the same checkout
rm -f ${ziparchive}
echo 'Creating the GAP core archive '${GAPCORE}/$ziparchive

cd ${DISTNAME}

# produce `configure` and `src/config.h.in`
./autogen.sh
if [[ -f configure ]]
then
  echo ${DISTNAME}'/configure' >> ../listbinaryfiles.txt
else
  echo 'no configure` file found!'
  exit 1
fi

if [[ -f src/config.h.in ]]
then
  echo ${DISTNAME}'/src/config.h.in' >> ../listtextfiles.txt
else
  echo 'no src/config.h.in` file found!'
  exit 1
fi

cd doc
pdftex gapmacrodoc.tex
pdftex gapmacrodoc.tex
cd ../..
echo ${DISTNAME}'/doc/gapmacrodoc.pdf' >> listbinaryfiles.txt

echo 'Adding text files to the archive '${GAPCORE}/$ziparchive
cat listtextfiles.txt | zip -q ${ziparchive} -@

echo 'Adding binary files to the archive '${GAPCORE}/$ziparchive
cat listbinaryfiles.txt | zip -q ${ziparchive} -@
             
exit 0


