#!/bin/sh -ex
#############################################################################
##

if [ ${DISTROOT}X==X ]; then
  echo 'Loading environment settings'
  source ./setvar
fi

export RELEASEBRANCH=${DISTROOT}/releasebranch

line='cd '${RELEASEBRANCH}
echo $line
$line 

source ./core_checkout_time.txt

ziparchive=${ARCHNAME}_release_branch${CORETIME}.zip
# we clean previous attempts to wrap the same checkout
rm -f ${ziparchive}

echo 'Adding text files to the archive '${RELEASEBRANCH}/$ziparchive
cat listtextfiles.txt | zip -q ${ziparchive} -@

echo 'Adding binary files to the archive '${RELEASEBRANCH}/$ziparchive
cat listbinaryfiles.txt | zip -q ${ziparchive} -@
             
exit 0
